server:
  port: 8090

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: player-service
          uri: lb://player-service
          predicates:
            - Path=/players/**

        - id: match-service
          uri: lb://match-service
          predicates:
            - Path=/matches/**
        
        - id: scorecard-service
          uri: lb://scorecard-service
          predicates:
            - Path=/scorecards/**
        
        - id: team-service
          uri: lb://team-service
          predicates:
            - Path=/teams/**


       
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
