server:
  port: 8090

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: player-service
          uri: lb://player-service
          predicates:
            - Path=/players/**

        - id: match-service
          uri: lb://match-service
          predicates:
            - Path=/matches/**
        
        - id: scorecard-service
          uri: lb://scorecard-service
          predicates:
            - Path=/scorecards/**
        
        - id: team-service
          uri: lb://team-service
          predicates:
            - Path=/teams/**

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

# Enable Actuator for health checks
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
